"""Report generation endpoint.

POST /reports/generate — collects tool results from a conversation, calls the
LLM to synthesize a narrative markdown report. Falls back to a structured
template if no LLM is configured.
"""
from __future__ import annotations

import json
import logging
from datetime import datetime
from typing import Any

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel

from app.agent.conversation import ConversationStore
from app.agent.llm import LLMReasoner

logger = logging.getLogger(__name__)
router = APIRouter()

_store = ConversationStore()

_REPORT_SYSTEM_PROMPT = (
    "You are a senior data analyst writing a concise, professional analysis report in Markdown. "
    "Structure the report with clear sections: Executive Summary, Dataset Overview, Key Findings "
    "(with sub-sections per analysis type), and Recommendations. "
    "Write for a technical but non-expert audience. Be specific — cite actual numbers from the findings. "
    "Do not fabricate data. If a section has no findings, omit it. "
    "Use Markdown formatting: ## for sections, ### for sub-sections, bullet points for lists, "
    "**bold** for important numbers. Keep the total length under 600 words."
)

_TOOL_LABELS = {
    "profile_dataset": "Dataset Profile",
    "data_quality_report": "Data Quality",
    "anomaly_scan": "Anomaly Detection",
    "explain_anomaly": "Anomaly Explanation",
    "correlation_analysis": "Correlation Analysis",
    "trend_analysis": "Trend Analysis",
    "kmeans_clusters": "Cluster Analysis",
    "auto_insights": "Auto Insights",
    "hypothesis_test": "Hypothesis Testing",
    "estimate_causal_effect": "Causal Inference",
    "cross_dataset_profile": "Cross-Dataset Analysis",
    "train_supervised_model": "Model Training",
    "score_with_model": "Model Scoring",
    "evaluate_trained_model": "Model Evaluation",
    "evaluate_ml_predictions": "Prediction Evaluation",
}

_KEEP_FIELDS = {
    "engineering_readout", "n_rows", "n_cols", "n_anomalies", "anomaly_rate_pct",
    "n_observations", "ate", "p_value", "significant_at_05", "effect_magnitude",
    "e_value", "r_squared", "findings", "summary_stats", "primary_metric",
    "primary_metric_value", "model_type", "target_col", "task_type",
    "beats_baseline", "t_statistic", "chi2_statistic", "f_statistic",
    "significant", "cohens_d", "cramers_v", "eta_squared", "pearson_r",
    "spearman_r", "required_n_per_group", "achieved_power",
    "n_datasets_compared", "n_high_correlations",
    "mean_a", "mean_b", "group_a", "group_b", "n_a", "n_b",
    "test_type", "col_a", "col_b", "treatment_col", "outcome_col",
}


def _slim_result(r: dict[str, Any]) -> dict[str, Any]:
    return {k: v for k, v in r.items() if k in _KEEP_FIELDS and not isinstance(v, (list, dict))}


def _collect_tool_results(conversation_id: str) -> list[dict[str, Any]]:
    conv = _store.get_or_create(conversation_id)
    seen: dict[str, dict[str, Any]] = {}
    for turn in conv.turns:
        for tr in turn.tool_results:
            if not isinstance(tr, dict):
                continue
            name = tr.get("name", "")
            if tr.get("ok") and name in _TOOL_LABELS:
                seen[name] = tr  # last occurrence wins
    return list(seen.values())


def _template_report(
    tool_results: list[dict[str, Any]], dataset_id: str | None
) -> str:
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    lines = [
        "# Data Analysis Report",
        f"*Generated: {now}*",
        "",
        "---",
        "",
    ]

    # Executive summary — pull first readout we find
    readouts = [
        str(tr["result"].get("engineering_readout", ""))
        for tr in tool_results
        if tr.get("result") and tr["result"].get("engineering_readout")
    ]
    if readouts:
        lines += ["## Executive Summary", "", readouts[0], ""]

    # Per-tool sections
    for tr in tool_results:
        name = tr.get("name", "")
        label = _TOOL_LABELS.get(name, name)
        result = tr.get("result") or {}
        readout = result.get("engineering_readout", "")

        lines += [f"## {label}", ""]
        if readout:
            lines.append(str(readout))
            lines.append("")

        slim = _slim_result(result)
        metrics = {k: v for k, v in slim.items() if k != "engineering_readout"}
        if metrics:
            for k, v in list(metrics.items())[:8]:
                lines.append(f"- **{k.replace('_', ' ').title()}**: {v}")
            lines.append("")

    lines += [
        "---",
        "*Report generated by Data Analyst Agent*",
    ]
    return "\n".join(lines)


def _llm_report(
    reasoner: LLMReasoner, tool_results: list[dict[str, Any]]
) -> str:
    summary_payload: dict[str, Any] = {"findings": []}
    for tr in tool_results:
        name = tr.get("name", "")
        result = tr.get("result") or {}
        slim = _slim_result(result)
        if result.get("engineering_readout"):
            slim["engineering_readout"] = str(result["engineering_readout"])
        summary_payload["findings"].append({"tool": _TOOL_LABELS.get(name, name), **slim})

    messages = [
        {"role": "system", "content": _REPORT_SYSTEM_PROMPT},
        {"role": "user", "content": json.dumps(summary_payload)},
    ]
    try:
        return reasoner._chat(messages, operation="report")
    except Exception as exc:
        logger.warning("LLM report generation failed: %s", exc)
        return ""


class ReportRequest(BaseModel):
    conversation_id: str
    use_llm: bool = True


class ReportResponse(BaseModel):
    report: str
    format: str = "markdown"
    source: str  # "llm" or "template"
    n_findings: int


@router.post("/reports/generate", response_model=ReportResponse)
def generate_report(body: ReportRequest) -> ReportResponse:
    tool_results = _collect_tool_results(body.conversation_id)
    if not tool_results:
        raise HTTPException(
            status_code=422,
            detail="No analysis results found for this conversation. Run some queries first.",
        )

    conv = _store.get_or_create(body.conversation_id)
    dataset_id = conv.last_dataset_id

    source = "template"
    report = ""

    if body.use_llm:
        reasoner = LLMReasoner()
        if reasoner.enabled:
            report = _llm_report(reasoner, tool_results)
            if report:
                source = "llm"

    if not report:
        report = _template_report(tool_results, dataset_id)
        source = "template"

    return ReportResponse(
        report=report,
        format="markdown",
        source=source,
        n_findings=len(tool_results),
    )
